In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [4]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [5]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [8]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [9]:
print(np.arange(0,21,3))

[ 0  3  6  9 12 15 18]


In [10]:
print(np.random.rand(5))

[0.74783743 0.67209118 0.54314839 0.07063379 0.08838405]


In [13]:
print(np.random.randint(1,50,5))

[21 49 30 21 15]


In [14]:
p=np.array([[1,2,3],[4,5,6]])
print(p)

[[1 2 3]
 [4 5 6]]


In [15]:
print(p.shape)

(2, 3)


In [16]:
print(p.ndim)

2


In [18]:
print(p.size)


6


In [19]:
print(p.dtype)

int64


In [21]:

q=p.reshape(3,2)
print(q)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
a=np.array([10,20,30])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)

[14 25 36]
[ 6 15 24]
[ 40 100 180]


In [23]:
r=np.array([10,20,30,40,50])
print(np.sum(r))

150


In [24]:
print(np.mean(r))

30.0


In [25]:
print(np.median(r))

30.0


In [26]:
print(np.std(r))

14.142135623730951


In [27]:
print(np.var(r))

200.0


In [28]:
print(np.min(r))

10


In [29]:
print(np.max(r))

50


In [31]:
print(p.T)

[1 2 3 4 5 6]
