In [14]:
import numpy as np
d=np.array([[10,20,30],[40,50,60]])
d

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
d.shape

(2, 3)

In [18]:
d.size

6

In [19]:
d.dtype

dtype('int64')

In [20]:
d.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
np.split(d,2)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

In [22]:
np.isnan(d)

array([[False, False, False],
       [False, False, False]])

In [24]:
np.mean(d)

np.float64(35.0)

In [25]:
np.sum(d)

np.int64(210)

In [26]:
np.median(d)

np.float64(35.0)

In [27]:
np.std(d)

np.float64(17.07825127659933)

In [29]:
np.min(d)


np.int64(10)

In [30]:
np.max(d)

np.int64(60)

In [31]:
np.random.randint(1,10,5)

array([2, 6, 2, 7, 6], dtype=int32)