In [1]:
import numpy as np

In [2]:
#Create a NumPy array from this list:[10, 20, 30, 40, 50]

a  = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [3]:
'''Create:
array of zeros (size 5)
array of ones (size 5)
array of numbers from 1 to 10'''

print(np.zeros(5))
print(np.ones(5))
print(np.arange(1,11))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#Generate numbers from 0 to 100 with step 5 using Numpy

print(np.arange(0,100,5))

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [5]:
#Create an array of 10 random numbers between 0 and 1.

print(np.random.rand(10))

[0.23654149 0.04876774 0.63536663 0.18185714 0.54871808 0.10132632
 0.49765392 0.90234136 0.48188709 0.58440849]


In [6]:
'''For an array:

arr = np.array([[1,2,3],[4,5,6]])
Find:
shape
size
dimensions
datatype '''

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64
